export const SEARCH_HOUSES = 'SEARCH_HOUSES';
export const SET_LOADING = 'SET_LOADING';
export const SET_FILTER_NAME = 'SET_FILTER_NAME';
export const SET_FILTERS = 'SET_FILTERS';
export const FILTER_HOUSES_NAME = 'FILTER_HOUSES_NAME';
export const ORDER_HOUSES = 'ORDER_HOUSES';
export const FILTER_HOUSES_ATTRIBUTES = 'FILTER_HOUSES_ATTRIBUTES';
